# Generated by Django 4.2 on 2024-12-05 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(db_index=True, max_length=100, unique=True)),
                ('path', models.CharField(blank=True, db_index=True, max_length=1024, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('desmontagem', 'Desmontagem'), ('montagem', 'Montagem')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C-EQUIPAMENTO', 'Chegada'), ('E-DESMONTADO', 'Desmontado'), ('E-PRONTO', 'Pronto'), ('E-MONTAGEM', 'Montagem'), ('E-TESTE', 'Teste')], max_length=15)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='imagens.sector')),
            ],
        ),
        migrations.CreateModel(
            name='StepOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_os', to='imagens.os')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_os', to='imagens.step')),
            ],
        ),
        migrations.AddField(
            model_name='os',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='imagens.sector'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=imagens.models.upload_to_server)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('step_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imagens.stepos')),
            ],
        ),
    ]
