# Generated by Django 4.2 on 2024-08-20 18:51

from django.db import migrations, models
import django.db.models.deletion
import imagens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('desmontagem', 'Desmontagem'), ('montagem', 'Montagem')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chegada', 'Chegada'), ('desmontado', 'Desmontado'), ('pronto', 'Pronto'), ('montagem', 'Montagem'), ('teste', 'Teste')], max_length=12)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='imagens.sector')),
            ],
        ),
        migrations.CreateModel(
            name='StepOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_os', to='imagens.os')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_os', to='imagens.step')),
            ],
        ),
        migrations.AddField(
            model_name='os',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='imagens.sector'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=imagens.models.upload_to_server)),
                ('step_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imagens.stepos')),
            ],
        ),
    ]
