# Generated by Django 4.2 on 2024-08-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='nome',
            field=models.CharField(choices=[('C', 'Chegada'), ('D', 'Desmontado'), ('P', 'Pronto'), ('M', 'Montagem'), ('T', 'Teste')], max_length=1),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(choices=[('D', 'Desmontagem'), ('M', 'Montagem')], max_length=1),
        ),
    ]
