# Generated by Django 4.2 on 2024-12-09 15:01

from django.db import migrations, models
import imagens.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(max_length=1000, upload_to=imagens.models.upload_to_server),
        ),
    ]
