# Generated by Django 4.2 on 2024-09-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='os',
            name='os',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
