# Generated by Django 4.2 on 2024-12-10 14:34

from django.db import migrations, models
import imagens.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=1000, upload_to=imagens.models.upload_to_server),
        ),
    ]
