# Generated by Django 4.2 on 2024-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_os_path_alter_os_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(choices=[('C-CHEGADA', 'Chegada'), ('E-DESMONTADO', 'Desmontado'), ('E-PRONTO', 'Pronto'), ('E-MONTAGEM', 'Montagem'), ('E-TESTE', 'Teste')], max_length=12),
        ),
    ]
