# Generated by Django 4.2 on 2025-02-21 14:50

from django.db import migrations, models
import django.db.models.deletion
import imagens.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(max_length=1000, upload_to=imagens.models.upload_to_server)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='imagens.stepos')),
            ],
        ),
    ]
