# Generated by Django 4.2 on 2024-08-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0003_imagem_path_alter_imagem_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='path',
        ),
    ]
