# Generated by Django 4.2 on 2024-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0003_alter_step_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(choices=[('C-EQUIPAMENTO', 'Chegada'), ('E-DESMONTADO', 'Desmontado'), ('E-PRONTO', 'Pronto'), ('E-MONTAGEM', 'Montagem'), ('E-TESTE', 'Teste')], max_length=15),
        ),
    ]
