# Generated by Django 4.2 on 2024-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0004_remove_imagem_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
