# Generated by Django 4.2 on 2024-12-05 16:37

from django.db import migrations, models
import imagens.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0004_alter_step_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=imagens.models.upload_to_server),
        ),
    ]
