# Generated by Django 4.2 on 2024-08-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0005_imagem_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
