# Generated by Django 4.2 on 2024-08-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0006_alter_imagem_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='.'),
        ),
    ]
