# Generated by Django 4.2 on 2024-08-14 01:26

from django.db import migrations, models
import imagens.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0007_alter_imagem_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='path',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to=imagens.models.upload_to_server),
        ),
    ]
