# Generated by Django 4.2 on 2024-08-14 02:12

from django.db import migrations, models
import django.db.models.deletion
import imagens.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0008_remove_imagem_path_alter_imagem_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=imagens.models.upload_to_server)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('desmontagem', 'Disassembly'), ('montagem', 'Assembly')], max_length=11)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='imagens.os')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chegada', 'Arrival'), ('desmontado', 'Disassembled'), ('pronto', 'Ready'), ('montagem', 'Assembly'), ('teste', 'Test')], max_length=12)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='imagens.sector')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='os',
        ),
        migrations.DeleteModel(
            name='Etapa',
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
        migrations.AddField(
            model_name='image',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imagens.step'),
        ),
    ]
